package com.pbaltazar.blindo.entities.enums

enum class MembershipState {
    SUBSCRIPTION_STATE_UNSPECIFIED,
    SUBSCRIPTION_STATE_PENDING,
    SUBSCRIPTION_STATE_ACTIVE,
    SUBSCRIPTION_STATE_PAUSED,
    SUBSCRIPTION_STATE_IN_GRACE_PERIOD,
    SUBSCRIPTION_STATE_ON_HOLD,
    SUBSCRIPTION_STATE_CANCELED,
    SUBSCRIPTION_STATE_EXPIRED
}
