-keep class java.util.Date
-keep class org.json.JSONObject
-keep class com.pbaltazar.blindo.graphql.** { *; }
-keep class com.blindoapp.blindoapi.** { *; }
-keep class com.apollographql.apollo.api.ScalarType
-keep class com.apollographql.apollo.api.CustomTypeAdapter
-keep class com.apollographql.apollo.ApolloClient
-keep class okhttp3.OkHttpClient
-keep class okhttp3.logging.HttpLoggingInterceptor
