name: Deploy Blindo version

on:
  workflow_call:
    inputs:
      packageType:
        description: Type of package to compile, possible values are 'apk' or 'aab'
        type: string
        required: true
      variant:
        description: Variant to compile, possible values are release, beta or debug
        type: string
        required: true
      enableDownload:
        description: If the compiled app should be available to download in artifacts
        type: boolean
        required: false
        default: false
      shouldPublishInPlayConsole:
        description: If the compiled app should be published in Play Console
        type: boolean
        required: true
      track:
        description: Release type in Play Console, possible values are production, beta, alpha, internal, internalsharing or a custom track
        type: string
      userFraction:
        description: Percentage of users who should get this release
        type: number
      inAppUpdatePriority:
        description: Priority for inApp updates where 0 represents a minimum priority and 5 the higher one
        type: number
    outputs:
      internalSharingDownloadUrls:
        description: A JSON list containing the download urls for every release file uploaded using the internalsharing track
        value: ${{ jobs.deploy-package.outputs.internalSharingDownloadUrls }}


jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    outputs:
      internalSharingDownloadUrls: ${{ steps.publish-in-play-console.outputs.internalSharingDownloadUrls }}
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v3
      - id: generate-secrets
        name: Generate secrets
        env:
          ENCODED_STORE: ${{ secrets.KEYSTORE_ENCODED_STORE }}
          STORE_FILE: 'keystore.jks'
          STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          DEBUG_ENCODED_STORE: ${{ secrets.KEYSTORE_DEBUG_ENCODED_STORE }}
          DEBUG_STORE_PASSWORD: ${{ secrets.KEYSTORE_DEBUG_STORE_PASSWORD }}
          DEBUG_KEY_ALIAS: ${{ secrets.KEYSTORE_DEBUG_KEY_ALIAS }}
          DEBUG_KEY_PASSWORD: ${{ secrets.KEYSTORE_DEBUG_KEY_PASSWORD }}
          BLINDO_API_URL: ${{ secrets.APP_BLINDO_API_URL }}
          ADMOB_PUBLISHER_ID: ${{ secrets.aDMOB_PUBLISHER_ID }}
          ADMOB_APPLICATION_ID: ${{ secrets.ADMOB_APPLICATION_ID }}
          ADMOB_MAIN_BANNER: ${{ secrets.ADMOB_MAIN_BANNER }}
          ADMOB_UPLOAD_PACK_BANNER: ${{ secrets.ADMOB_UPLOAD_PACK_BANNER }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FACEBOOK_APPLICATION_ID: ${{ secrets.AUTH_FACEBOOK_APPLICATION_ID }}
          FB_LOGIN_PROTOCOL_SCHEME: ${{ secrets.AUTH_FACEBOOK_LOGIN_PROTOCOL_SCHEME }}
          TWITTER_CONSUMER_KEY: ${{ secrets.AUTH_TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.AUTH_TWITTER_CONSUMER_SECRET }}
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/*
          bash ${GITHUB_WORKSPACE}/.github/scripts/generate-keystore-configuration.sh
          bash ${GITHUB_WORKSPACE}/.github/scripts/generate-gradle-secrets.sh
          bash ${GITHUB_WORKSPACE}/.github/scripts/generate-google-services-json.sh
          bash ${GITHUB_WORKSPACE}/.github/scripts/generate-firebase-auth-secrets.sh
      - id: build-artifact
        name: Build artifact
        if: success()
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/compile-package.sh ${{ inputs.packageType }} ${{ inputs.variant }}
      - id: upload-artifact
        if: |
          success() &&
          inputs.enableDownload &&
          steps.build-artifact.outputs.package-file-path != null
        uses: actions/upload-artifact@v3
        with:
          name: blindo-package
          path: ${{ steps.build-artifact.outputs.package-file-path }}
      - id: publish-in-play-console
        if: |
          success() &&
          inputs.shouldPublishInPlayConsole &&
          steps.build-artifact.outputs.package-file-path != null
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.PLAY_CONSOLE_SERVICE_ACCOUNT }}
          packageName: com.pbaltazar.blindo
          releaseFiles: ${{ steps.build-artifact.outputs.package-file-path }}
          track: ${{ inputs.track }}
          userFraction: ${{ inputs.userFraction }}
          inAppUpdatePriority: ${{ inputs.inAppUpdatePriority }}
          mappingFile: ${{ steps.build-artifact.outputs.mapping-file-path }}
          whatsNewDirectory: ${GITHUB_WORKSPACE}/assets/whatsnew
