name: Deploy manually

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      packageType:
        description: Type of package to compile
        type: choice
        required: true
        options:
          - AAB
          - APK
      variant:
        description: Variant to compile
        type: choice
        required: true
        options:
          - Release
          - Beta
          - Debug
      shouldUpdateVersionName:
        description: Auto update version name
        type: boolean
        required: true
      versionNameUpdateLevel:
        description: Level to update version name
        type: choice
        required: true
        options:
          - Patch
          - Minor
          - Major
      enableDownload:
        description: The compiled app should be available to download in artifacts
        type: boolean
        required: true
      shouldPublishInPlayConsole:
        description: Publish app in Play Console
        type: boolean
        required: true
      track:
        description: Type of publish
        type: choice
        required: false
        options:
          - Production
          - Beta
          - Internal
      inAppUpdatePriority:
        description: InApp update priority (0=lower and 5=highest)
        type: string
        required: false
        default: 0

jobs:
  deploy:
    uses: ./.github/workflows/deploy-blindo-version.yaml
    secrets: inherit
    with:
      packageType: ${{ inputs.packageType }}
      variant: ${{ inputs.variant }}
      shouldUpdateVersionName: ${{ inputs.shouldUpdateVersionName }}
      versionNameUpdateLevel: ${{ inputs.versionNameUpdateLevel }}
      enableDownload: ${{ inputs.enableDownload }}
      shouldPublishInPlayConsole: ${{ inputs.shouldPublishInPlayConsole }}
      track: ${{ inputs.track }}
      inAppUpdatePriority: ${{ inputs.inAppUpdatePriority }}
