name: Deploy from push

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'version.gradle'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-blindo-version.yaml
    secrets: inherit
    with:
      packageType: aab
      variant: release
      enableDownload: false
      shouldPublishInPlayConsole: true
      track: internal
      userFraction: 1.0
      inAppUpdatePriority: 5
