name: Deploy manually

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      packageType:
        description: Type of package to compile
        type: choice
        required: true
        options:
          - APK
          - AAB
      variant:
        description: Variant to compile
        type: choice
        required: true
        options:
          - Release
          - Beta
          - Debug
      enableDownload:
        description: The compiled app should be available to download in artifacts
        type: boolean
        required: true
      shouldPublishInPlayConsole:
        description: Publish app in Play Console
        type: boolean
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-blindo-version.yaml
    secrets: inherit
    with:
      packageType: ${{ inputs.packageType }}
      variant: ${{ inputs.variant }}
      enableDownload: ${{ inputs.enableDownload }}
      shouldPublishInPlayConsole: ${{ inputs.shouldPublishInPlayConsole }}
      track: beta
      userFraction: 1.0
      inAppUpdatePriority: 5
