name: Deploy from tag

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    environment: production
    uses: ./.github/workflows/deploy-blindo-version.yaml
    secrets: inherit
    with:
      packageType: aab
      variant: ${{ secrets.VARIANT }}
      enableDownload: false
      shouldPublishInPlayConsole: true
      track: beta
      userFraction: 1.0
      inAppUpdatePriority: 5
