name: Deploy from tag

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_blindo_version_from_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Blindo version
        uses: ./.github/workflows/deploy-blindo-version.yaml
        with:
          track: internal
          userFraction: 1.0
          inAppUpdatePriority: 5
          secrets: inherit
