name: Deploy from version code

concurrency:
  group: deploy-blindo-version
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'version.gradle'
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'version.gradle'

jobs:
  deploy_blindo_version_from_version_code:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Blindo version
        uses: ./.github/workflows/deploy-blindo-version.yaml
        with:
          track: internal
          userFraction: 1.0
          inAppUpdatePriority: 5
          secrets: inherit
